title: "Towards Urban General Intelligence Through Urban Foundation Models"
description: "ACM KDD 2024 Tutorial, | Barcelona, Spain <br/>
Weijia Zhang, Jindong Han, Zhao Xu, Hang Ni, Hao Liu, Hui Xiong"
header_text: KDD 2024 Tutorial
theme: jekyll-theme-slate
