title: "Towards Urban General Intelligence Through Urban Foundation Models"
description: "ACM KDD 2024 Tutorial, | Barcelona, Spain <br/>
Weijia Zhang, Jindong Han, Zhao Xu, Hang Ni, Hao Liu, Hui Xiong <br/>
Sunday, August 25, 2024 | 9:00 AM - 12:30 PM | Room: TBA <br/>"
header_text: KDD 2024 Tutorial
theme: jekyll-theme-slate
