title: "Towards Urban General Intelligence Through Urban Foundation Models"
description: "ACM KDD 2024 Tutorial | Barcelona, Spain <br/>
Hao Liu, Weijia Zhang, Jindong Han, Zhao Xu, Hang Ni, Hui Xiong <br/>
Sunday, August 25, 2024 | 2:00 PM - 5:00 PM | Room: Area 134 <br/>"
header_text: KDD 2024 Tutorial
theme: jekyll-theme-slate
google_analytics: G-Y00QMX21NQ
